
output: ModularityExample.o ModularityNonExample.o
    g++ ModularityExample.o ModularityNonExample.o
    
ModularityExample.o: ModularityExample.cpp
    g++ -c ModularityExample.cpp
    
ModularityNonExample.o: ModularityNonExample.cpp
    g++ -c ModularityNonExample.cpp
    
clean:
    rm *.o output